### ISSUE TITLE
컴포넌트 관계도 그리기

### ISSUE THREAD

**Issue by dhkim511** [nakyeonko3/devcamp-onboarding-04#10]
각 기능별 컴포넌트 다이어그램 그리기

- [x] 1 로그인 기능
- [x] 2 프로필 조회 기능
- [x] 3 포트폴리오 업로드 및 조회 기능
- [x] 4 직무 적성 테스트 프로그램
- [x] 5 구직자 매칭 및 기업 추천 기능
- [x] 컴포넌트 다이어그램 내용을 기능정의서에 넣기

**Comment by badaclockA** [comment]
김도형님께서 올려주신 컴포넌트 관계도 예시
```
[사용자 인터페이스] <---> [회원 관리 시스템] <---> [데이터베이스]
       |                            |
       v                            v
[구직 관리 시스템] <---> [구인 관리 시스템]
       |                            |
       v                            v
[적성 검사 모듈] <-----> [알림 시스템]
```

**Comment by badaclockA** [comment]
[참고]
컴포넌트 다이어그램 그리기 관련 영상
[UML기초 06 - 컴포넌트 다이어그램](https://www.youtube.com/watch?v=SzG5rz6G8ls)

**Comment by ghost** [comment]
포트폴리오 업로드 및 조회 기능
---
```mermaid
flowchart TD
    A[Portfolio] --> B[updatePortfolio]
    A --> C[searchPortfolio]
    B --> D[updateImages]
    B --> E[updateDocuments]
    B --> F[updateVideos]
    B --> I[submitButton]
    C --> G[isPublic]
    C --> H[portfolioList]
    J[Button] --> I
```
포트폴리오 부모 컴포넌트에 포트폴리오 업로드 컴포넌트와 포트폴리오 조회 컴포넌트가 존재합니다.
포트폴리오에 업로드 할 수 있는 자료는 pdf 등 문서, 이미지 파일, 동영상 파일 이므로 각각을 업로드하기 위한 컴포넌트와 저장할 수 있는 버튼 컴포넌트가 'updatePortfolio' 컴포넌트에 존재합니다. 
공개 설정된 포트폴리오에 한해 조회 가능하므로 공개 여부를 알아내기 위한 'isPublic' 컴포넌트와 조회할 포트폴리오를 배열에 담아 보여줄 'portfolioList' 컴포넌트가 포트폴리오 조회 컴포넌트에 존재합니다.

**Comment by dhkim511** [comment]
### 로그인 기능

![스크린샷 2024-05-23 154658](https://github.com/nakyeonko3/devcamp-onboarding-04/assets/143858798/b3aff7ac-c20f-4f20-8eda-a2985fbb5d02)

1. 기존 사용자 

    로그인 페이지로 이동해 정보를 입력하면 그 정보를 데이터베이스에 인증하는 단계를 거쳐 일치하면 로그인이 되고

    불일치하면 다시 로그인 페이지로 돌아와서 입력하는 과정



2. 신규 사용자

   회원가입 페이지로 이동해 회원가입을 완료하고 가입 정보를 데이터베이스에 저장하는 과정과 이후 로그인 과정을 나타내는
 
   과정

**Comment by JunhyeongSong** [comment]
**프로필 조회 기능 컴포넌트 관계도**

직무 적성 온라인 채용 플랫폼 프로필 조회 기능의 컴포넌트 관계도는 프로필 공개 범위 설정과 검색 및 필터링 기능 등의 상호작용과 의존성을 보여주며, 사용자 프로필 조회, 공개 범위 설정, 검색 및 필터링 기능 등을 구현하는 데 사용된다.

<img width="1483" alt="프로필 조회 기능(컴포넌트 관계도)" src="https://github.com/nakyeonko3/devcamp-onboarding-04/assets/146011623/91d1bd96-116d-429f-afc1-dd130a2ad0d4">

**Comment by BES9507** [comment]
[mermaid-history-2024-05-23-155649.json](https://github.com/nakyeonko3/devcamp-onboarding-04/files/15412922/mermaid-history-2024-05-23-155649.json)

**Comment by BES9507** [comment]
[![](https://mermaid.ink/img/pako:eNpVkc1Kw0AQx19l2ZNC-gI5CK1powdPejMelmRri00iMUFkCSjES1HSQ4NFo1SoLUKFaFupr5TMvoP5ssTdy8x_fjPMB8OqqVEs4nbPvFQ7xLLRkaQYKH3143g1h9kNvAxQMpvAzwdKIh_F6wgebhF8D-ErzLyk_3aCarWdxlaFv4_gecm9aLuslQFol5XJm7CbyXLBNHJGYnzoJa8hDzy3qjcZ9-e8v-b-MpnOYTT5F20xmF3D04AHIYJPDx7f48UqXoxLSMohmdX3BQjuUj0rMR2V0SaqdNGqOnLu7LHNYMLfAPk-ynzFKH5hI4QFrFNLJ10t3SvLFAXbHapTBYupqRHrTMGK4aYccWzz8MpQsWhbDhWwc64Rm0pdcmoRHYtt0rtIVap1bdM6KA6V38v9BULquwM?type=png)](https://mermaid.live/edit#pako:eNpVkc1Kw0AQx19l2ZNC-gI5CK1powdPejMelmRri00iMUFkCSjES1HSQ4NFo1SoLUKFaFupr5TMvoP5ssTdy8x_fjPMB8OqqVEs4nbPvFQ7xLLRkaQYKH3143g1h9kNvAxQMpvAzwdKIh_F6wgebhF8D-ErzLyk_3aCarWdxlaFv4_gecm9aLuslQFol5XJm7CbyXLBNHJGYnzoJa8hDzy3qjcZ9-e8v-b-MpnOYTT5F20xmF3D04AHIYJPDx7f48UqXoxLSMohmdX3BQjuUj0rMR2V0SaqdNGqOnLu7LHNYMLfAPk-ynzFKH5hI4QFrFNLJ10t3SvLFAXbHapTBYupqRHrTMGK4aYccWzz8MpQsWhbDhWwc64Rm0pdcmoRHYtt0rtIVap1bdM6KA6V38v9BULquwM)


구직자 매칭 및 기업 추천 기능은 기업 데이터, 구직자 데이터를 AI,알고리즘,머신러닝을 이용해 기업과 구직자간의 상성이 좋은 매칭을 시켜준다.

**Comment by badaclockA** [comment]
## 직무적성 테스트 프로그램

- 검사지 웹페이지
사용자는 검사지 웹페이지를 통해 직무적성검사를 진행 할 수 있다.

- 유효성 검사 프로그램
사용자가 검사자에 입력한 정보에 대한 유효성을 검증한다. 
예) 특정 질문 미답, 질문 글자수 초과 등에 대한 유효성 검증

- 검사지 결과 분석 프로그램
검사지에 대한 분석 결과를 계산하고 결과를 검사지 관리 프로그램에 보냅니다.

- 검사지 관리 프로그램
관리자가 검사지 수정, 검사지 삭제, 검사지 등록, 검사지 내용을 확인 하는 기능을 가지고 있습니다.

- 데이터베이스
검사지, 검사결과, 직무추천결과, 사용자 데이터 등이 저장이 되어 있습니다.

![](https://i.imgur.com/hyA2E6g.png)
