### ISSUE TITLE
다이어그램 그리기 

### ISSUE THREAD

**Issue by badaclockA** [nakyeonko3/devcamp-onboarding-04#4]

**Comment by badaclockA** [comment]
다이어그램 그리기 예시
![](https://i.imgur.com/2cTXoT7.png)

**Comment by dhkim511** [comment]
![스크린샷 2024-05-22 165123](https://github.com/nakyeonko3/devcamp-onboarding-04/assets/143858798/fd9d558c-22ee-470d-b6f0-36fc91675558)

**Comment by codeJunH** [comment]
![image](https://github.com/nakyeonko3/devcamp-onboarding-04/assets/146011623/269e03bc-2764-4501-b6ec-de36340c6961)

**Comment by JunhyeongSong** [comment]
![image](https://github.com/nakyeonko3/devcamp-onboarding-04/assets/146011623/d839fffa-82ee-4871-b136-45da25b0d0f1)
